name: xnap-example
channels:
  - pytorch
  - defaults
dependencies:
  - collections
  - numpy
  - tqdm
  - pytorch
  - tensorboard
  - python=3.8
  - pip
  - protobuf[version='<=3.20']
  - pip:
    - ipykernel
    - ipython
    - joblib
    - matplotlib
    - nltk
    - onnx
    - pandas
    - pillow
    - scikit-learn
    - spacy
    - torchaudio
    - torchvision
    - wandb
